langs = {
    'en': {
        'select_language': 'Language selected',
        'registration': 'To register, share your contact',
        'contact': 'Share contact',
        'reg_complete': "Registration completed successfully. To get information about the bot's abilities, "
                        "enter the command: /help",
        'help': "Hello, I'm a bot that can book for you, air tickets, hotel rooms or a table in a restaurant "
                "by calling the /booking command. Also you can cancel your bookings by calling the /cancel coomand",
        'booking': 'Choose option',
        'reserve': 'Booking',
        'settings': 'Settings',
        'category': 'Choose category',
        'air_tickets': 'Air tickets',
        'hotels': 'Hotels',
        'restaurants': 'Restaurants',
        'museums': 'Museums',
        'special': 'Special events',
        'period': 'Choose period',
        'back': '⬅ Back',
        'date_selected': 'Date selected: ',
        'time': 'Enter time of your reserving in format 12:00',
        'people': 'Enter amount of people',
        'zero': 'You cant go below zero',
        'book': '✅ Book',
        'booking_error': 'It is not possible to book. Try again',
        'booking_successful': 'You successfully booked',
        'booking_unavailable': 'It is not possible to book for this date or time',
        'choose_alternative': 'Choose another date or time for reserving',
        'choose_booking': 'Choose booking for cancel: ',
        'cancel': '❌ Cancel booking',
        'booking_name': 'Booking category',
        'booking_date': 'Booking date',
        'booking_time': 'Booking time',
        'booking_people': 'Amount of people',
        'booking_not_found': 'Booking not found',
        'booking_cancelled': 'Your booking cancelled successfully',
        'choose_option': 'Choose option',
        'change_lang': 'Change language',
        'select_lang': 'Select language',
        'reminder': 'Reminder! Your booking is scheduled for'
    },

    'ru': {
        'select_language': 'Язык выбран',
        'registration': 'Для регистрации поделитесь своими контактами',
        'contact': 'Поделитесь контактом',
        'reg_complete': 'Регистрация успешно завершена. Для получения информации о возможностях бота '
                        'введите команду: /help',
        'help': "Здравствуйте, я бот, который может забронировать для вас авиабилеты, номера в отелях или столик в ресторане, "
                "используя команду /booking. Также вы можете отменить свои брони вызвав команду /cancel",
        'booking': 'Выберите опцию',
        'reserve': 'Забронировать',
        'settings': 'Настройки',
        'category': 'Выберите категорию',
        'air_tickets': 'Авиабилеты',
        'hotels': 'Отели',
        'restaurants': 'Рестораны',
        'museums': 'Музеи',
        'special': 'Special-events',
        'period': 'Выберите период',
        'back': '⬅ Назад',
        'date_selected': 'Дата выбрана: ',
        'time': 'Введите время вашего бронирования в формате 12:00',
        'people': 'Введите количество людей',
        'zero': 'Вы не можете выбрать меньше нуля',
        'book': '✅ Забронировать',
        'booking_error': 'Не удалось забронировать. Попробуйте снова',
        'booking_successful': 'Вы успешно забронировали',
        'booking_unavailable': 'Не удается забронировать на эту дату или время',
        'choose_alternative': 'Выберите другую дату или время для бронирования',
        'choose_booking': 'Выберите бронь для отмены: ',
        'cancel': '❌ Отменить бронь',
        'booking_name': 'Категория бронирования',
        'booking_date': 'Дата бронирования',
        'booking_time': 'Время бронирования',
        'booking_people': 'Количество людей',
        'booking_not_found': 'Бронь не найдена',
        'booking_cancelled': 'Ваша бронь успешно удалена',
        'choose_option': 'Выберите опцию',
        'change_lang': 'Сменить язык',
        'select_lang': 'Выберите язык',
        'reminder': 'Напоминание! Ваша бронь запланирована на'
    },

    'uz': {
        'select_language': 'Til tanlandi',
        'registration': 'Ro‘yxatdan o‘tish uchun kontakt ma’lumotlaringizni ulashing',
        'contact': 'Kontaktni ulashish',
        'reg_complete': "Ro‘yxatdan o‘tish muvaffaqiyatli yakunlandi. Bot imkoniyatlari haqida ma'lumot olish uchun "
                        "quyidagi buyruqni kiriting: /help",
        'help': "Salom, men sizga aviachiptalarni, mehmonxona xonalarini yoki restoranlarda stolni buyurtma qilishda "
                "yordam beradigan botman. Buyurtma qilish uchun /booking buyrug‘ini kiriting. "
                "Shuningdek, buyurtmalaringizni bekor qilish uchun /cancel buyrug‘ini kirishingiz mumkin",
        'booking': 'Tanlovni qiling',
        'reserve': 'Buyurtma qilish',
        'settings': 'Sozlamalar',
        'category': 'Kategoriyani tanlang',
        'air_tickets': 'Aviabiletlar',
        'hotels': 'Mehmonxonalar',
        'restaurants': 'Restoranlar',
        'museums': 'Muzeylar',
        'special': 'Maxsus tadbirlar',
        'period': 'Davrni tanlang',
        'back': '⬅ Orqaga',
        'date_selected': 'Tanlangan sana: ',
        'time': 'Buyurtma vaqtini 12:00 formatda kiriting',
        'people': 'Odamlar sonini kiriting',
        'zero': 'Siz nolga tusholmaysiz',
        'book': '✅ Buyurtma qilish',
        'booking_error': 'Buyurtma qilishning imkoni yo‘q. Qayta urinib ko‘ring',
        'booking_successful': 'Siz muvaffaqiyatli buyurtma qildingiz',
        'booking_unavailable': 'Bu sana yoki vaqt uchun buyurtma qilishning imkoni yo‘q',
        'choose_alternative': 'Rezervatsiya uchun boshqa sana yoki vaqtni tanlang',
        'choose_booking': 'Bekor qilish uchun buyurtmani tanlang: ',
        'cancel': '❌ Buyurtmani bekor qilish',
        'booking_name': 'Buyurtma kategoriyasi',
        'booking_date': 'Buyurtma sanasi',
        'booking_time': 'Buyurtma vaqti',
        'booking_people': 'Odamlar soni',
        'booking_not_found': 'Buyurtma topilmadi',
        'booking_cancelled': 'Sizning buyurtmangiz muvaffaqiyatli bekor qilindi',
        'choose_option': 'Tanlang opciya',
        'change_lang': "Tilni ozgartiring",
        'select_lang': 'Tilni tanlang',
        'reminder': 'Eslatma! Sizning broningiz'
    }
}
